### ISSUE TITLE
this mod has a trojan virus.

### ISSUE THREAD

**Issue by ShadowWolfM60** [s1nk0/SPT-AKI-Mod-Manager#2]
why the fuck is there a trojan virus in this mod. the trojan is win32:backdoorX-gen.

**Comment by s1nk0** [comment]
> why the fuck is there a trojan virus in this mod. the trojan is win32:backdoorX-gen.

Apologies, these are most likely false positives. I'm not a good programmer so maybe it's detecting copying and pasting functions as a trojan.

**Comment by ShadowWolfM60** [comment]
no. it has win32:backdoorX-gen in it which is most definatly a trojan. so if it isnt that what the fuck is with the picture below?.

![Screenshot 2023-01-30 202442](https://user-images.githubusercontent.com/112789998/215646027-98c96c50-cd06-4bbc-932d-a4de7f96d01e.JPG)
