### ISSUE TITLE
this mod has a backdoor trojan and the dev has tried to play it off as nothing.

### ISSUE THREAD

**Issue by ShadowWolfM60** [s1nk0/SPT-AKI-Mod-Manager#3]
this mod is infected with Win32:backdoorX-gen type tojan virus. i have downloaded the zip manu times at different dates and it is definatly there. image below. 

![Screenshot 2023-01-30 202442](https://user-images.githubusercontent.com/112789998/215645297-c4c0b247-e1ed-4108-b2c2-96d6a3168658.JPG)

**Comment by s1nk0** [comment]
I deleted the files since I closed your previous issue.

**Comment by s1nk0** [comment]
Okay I deleted the last exe file. It should be clean now. Sorry again.

**Comment by s1nk0** [comment]
If you have any further concerns regarding the repo, please feel free to create a new issue.
